# Generated by Django 2.2.12 on 2022-05-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('recipe', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('quote', models.CharField(max_length=1000)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
