# Generated by Django 2.2.12 on 2022-05-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutcoffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=64)),
                ('name2', models.CharField(max_length=64)),
                ('text1', models.CharField(max_length=1000)),
                ('text2', models.CharField(max_length=1000)),
                ('quote', models.CharField(max_length=1000)),
                ('photo1', models.ImageField(upload_to='')),
                ('photo2', models.ImageField(upload_to='')),
            ],
        ),
    ]
